### ISSUE TITLE
license of this repo?

### ISSUE THREAD

**Issue by testing-account2022** [zhanjiawang/VPFBR-L#2]
Hi! what is the license of this work? Seems interesting!

**Comment by testing-account2022** [comment]
@zhanjiawang?

**Comment by zhanjiawang** [comment]
Hello, I have added the BSD License.

**Comment by zhanjiawang** [comment]
Hello, I have added the BSD License. @testing-account2022

**Comment by zhanjiawang** [comment]
Hello, I have added the MIT License. @testing-account2022

**Comment by testing-account2022** [comment]
thank you!
